



if(isServer && !isDedicated && !isNull player) then {

	player createDiarySubject ["SCT_VestFnc","SCT_options"];

	player createDiaryRecord ["SCT_VestFnc", ["Help/Credits", "

	<br/><br/>
	Made by Sonic.T. referenced from : RHS, CBA, ACE, and many more mods.\
	Rewritten and optimized by Sysroot.
	"]];
	player createDiaryRecord ["SCT_VestFnc", ["Settings", ("
	<br/>
	Click Below to Adjust Settings.<br/>
	<font color='#CC0001'><execute expression = 'call SCT_fnc_OpenSettings'>Options</execute></font color>
	")]];
	
	player createDiarySubject ["Docs","AAPM Documentation"];
	
	player createDiaryRecord ["Docs", ["System: NIJ 0101.07", "Successor standard to NIJ 0101.06. Modernizes the lower end of the scale and eliminates ratings for low-powered threats. All levels permit a maximum BFD of 44mm.<br/><br/>HG1: .357 Magnum JHP and 9x19mm FMJ at slightly higher velocity requirements than 0101.06 NIJ-II, 6 Shots<br/>HG2: .44 Magnum JHP at slightly higher requirements than 0101.06 NIJ-IIIA, 6 Shots<br/>RF1: 5.56x45mm and 7.62x51mm Ball and FMJ, 6 Shots<br/>RF2: 5.56x45mm M855 and 7.62x39mm MSC, 6 Shots<br/>RF3: .30-06 M2AP, 1 Shot"]];
	player createDiaryRecord ["Docs", ["System: NIJ 0101.06", "The nearly-universal body armor standard for American civilians. Relatively poor regulations on Backface Deformation but solid multi-hit requirements for most levels. Suffers from seemingly intentional inability to handle modern AP threats. All levels permit a maximum BFD of 44mm.<br/><br/>NIJ-I: .22LR and .380 ACP, 6 Shots<br/>NIJ-IIA: 9x19mm FMJ and .45 ACP FMJ, 6 Shots<br/>NIJ-II: 9x19mm FMJ and .357 Magnum JHP, 6 Shots<br/>NIJ-IIIA: 9x19mm FMJ (SMG) and .44 Magnum JHP, 6 Shots<br/>NIJ-III: 5.56x45mm M193 and 7.62x51mm M80, 6 Shots<br/>NIJ-III+: M855 or M61 or SS109, 6 Shots<br/>NIJ-III++: 7.62x39mm BZ API, 6 shots<br/>NIJ-IV: 30-06 M2AP, at least 1 shot<br/>NIJ-IV+: 7.62x54R B-32 API, 1 Shot or more<br/><br/>Additional Ratings:<br/>NIJ-IV-: Uncommon rating that calls for double-hit protection from either 7.62x39mm BZ API or 5.56x45mm SS109<br/>NIJ-III/IV-: Combination rating that certifies the plate is both Level III and Level IV rated ICW NIJ-IIIA soft armor<br/>NIJ-III/IV: Combination rating that certifies the standalone plate is both Level III and Level IV rated.<br/>NIJ-III/IV+: Combination rating that certifies the plate is rated at III and IV+ levels<br/>NIJ-IV++: Additional multi-hit protection from 7.62x54R and 7.62x39mm BZ API, an attempt at western GOST-6A.<br/>NIJ-IV+++: Single-hit protection from Winchester/Olin 7.62x51mm SLAP<br/>NIJ-V: Multiple-hit protection from 7.62x51mm M993, 5.56x45mm M995, 7.62x54R BS40 API, and 7.62x51mm M948."]];
	player createDiaryRecord ["Docs", ["System: MIL", "Semi-fictional universal standard for military body armor. Maximum BFD of 44mm. <br/><br/>MIL-III: Multiple-hit Protection from 5.56x45mm M855A1 FMJ and 7.62x51mm M80 Ball<br/>MIL-IV: Multiple-hit Protection from 30-06 M2AP and M855A1<br/>MIL-VA: Multiple-hit Protection from 5.56x45mm M995<br/>MIL-V: Multiple-hit Protection from 7.62x51mm M993, 5.56x45mm M995, 5.45x39mm 7N39, 7.62x54mm 7N37<br/>MIL-VI: Multiple-hit Protection from .338 Lapua Magnum or 7.62x51mm DUDS or 9.3x64mm 7N33<br/>MIL-VI+: Multiple-hit Protection from .338 Lapua Magnum or 7.62x51mm DUDS or 9.3x64mm 7N33<br/>MIL-VII: Multiple-hit Protection from 12.7x55mm STs-130 and .338 Lapua Magnum API526<br/>MIL-VIII: Single-hit Protection from 12.7x99mm Ball or 12.7x108mm Ball<br/>MIL-VIII*: Single-hit Protection from 12.7x99mm AP"]];
	player createDiaryRecord ["Docs", ["System: GOST R 50774-95 ADD. 2014", "Replacement for the original GOST R 50774-95 Standard. Identical emphasis on multi-hit protection and low BFD. Maximum BFD of 17mm.<br/><br/>GOST-БР1: 9x18 projectiles<br/>GOST-БР2: 9x21 7N28 AP handgun ammunition<br/> GOST-БР3: 9x19 7N21 AP handgun ammunition<br/> GOST-С1: 12-Gauge buckshot<br/> GOST-С2: 12-Gauge buckshot, 00 or 000<br/> GOST-БР4-I: Multiple impacts of 5.45x39mm 7N10 semi-armor-piercing ball<br/>GOST-БР4-II: Multiple impacts of 7.62x39mm 57-N-231 Steel-core, roughly on-par with NIJ Level III<br/>GOST-БР5-I: Multiple impacts of 7.62x54mm 7N13 Hardened Core<br/>GOST-БР5-II: Multiple impacts of 7.62x54mm 7-B3-B3-B32 API, slightly higher than NIJ Level IV<br/>GOST-БР6: Multiple impacts of 12.7x108mm B32 API, slightly stronger than MIL-VIII<br/>"]];
	player createDiaryRecord ["Docs", ["System: GOST R 50774-95", "Infamous body armor standard of the former Soviet Union and the modern Russian Federation. Replaced by the ADD. 2014 extension as of 2014. This system has an extremely high emphasis on low BFD and solid multi-hit capacity. Maximum BFD of 17mm.<br/><br/>GOST-1: 9x18mm FMJ, 5 Hits<br/>GOST-2: 5.45x39mm 7N7 and 7.62x39mm 57-H-134C, 5 Hits<br/>GOST-2A: 12-Gauge Slug, 5 Hits<br/>GOST-3: 5.45x39mm 7N6 and 7.62x39mm 57-H-231, 5-10 Hits<br/>GOST-4: 5.45x39mm 7N10, 5-10 Hits<br/>GOST-5A: 7.62x39mm 57-B3-231, 5-10 Hits<br/>GOST-6: 7.62x54R 7N13, 5-10 Hits<br/>GOST-6A: 7.62x54R B32 API, 5-10 Hits. Additionally provides .338 LM FMJ protection at 300 Meters"]];
	player createDiaryRecord ["Docs", ["System: FBI TESTING PROTOCOL", "The FBI's extremely potent Internal Rating System of body armor that is more difficult to pass than either NIJ 0101.07 or GOST 50774-95. Maximum BFD of 11mm. <br/><br/>FBI-II: Multiple hit protection from 9x19mm and .357 Magnum<br/>FBI-IIIA: Multiple hit protection from 5.7x28mm FN AP<br/>FBI-III: Multiple hit protection from 7.62x51mm M80 and 5.56x45mm M855A1, single hit protection from 5.56x45mm M995<br/>FBI-IV: Multiple hit protection from M993, M995, LC/70, 7N37, 7N39, and .338 Lapua Magnum FMJ, on-par with MIL-VI"]];
	player createDiaryRecord ["Docs", ["System: HOSDB 39/07/A", "British Home Office standards for Ballistic Armor. Completely inadequate body armor standard for military use, but acceptable for the Home Office.<br/><br/>HG1/A: 9x19mm FMJ and .357 Magnum JSP, 44mm BFD<br/>HG1: 9x19mm FMJ and .357 Magnum JSP, 25mm BFD<br/>HG2: 9x19mm and .357 Magnum at increased velocity, 25mm BFD<br/>HG3: 5.56x45mm NATO, 25mm BFD<br/>RF1: 7.62x51mm Ball, 25mm BFD<br/>RF2: High-powered 7.62x51mm Ball, 25mm BFD<br/>SG1: 12-Gauge Slug, 25mm BFD"]];
	player createDiaryRecord ["Docs", ["System: SK", "The body armor standard of Germany.<br/><br/>SKL: 9x19mm at 360 m/s<br/>SK1: 9x19mm at 460 m/s<br/>SK2: .357 Magnum at 580 m/s<br/>SK3: 5.56x45mm SS109 at 950 m/s and DM111 7.62x51mm at 830m/s<br/>SK4: Steel-core 7.62x51mm P80 at 820 m/s, on par with NIJ III<br/>SK5: Tungsten projectiles, roughly par with MIL-V or NIJ IV*"]];
	player createDiaryRecord ["Docs", ["System: NATO AEP-C", "Internal body armor standard of the North Atlantic Treaty Organization that covers traditional steel-core threats.<br/><br/>C4: 7.62x39mm API BZ<br/>C5: 7.62x51mm FN P80<br/>C6: 7.62x54mm B32 API<br/>C7: 30-06 M2AP<br/>C8: 12.7x108mm B32<br/>C-Special (C-S): Undetermined, Emerging Threat"]];
	player createDiaryRecord ["Docs", ["System: NATO AEP-D", "Internal body armor standard of the North Atlantic Treaty Organization that covers Tungsten AP threats.<br/><br/>D1: 9x19mm MEN AP<br/>D3: 5.56x45mm M995 / 5.56x45mm MEN AP DM31<br/>D5: 7.62x51mm M993<br/>D6: 7.62x54mm 7N37<br/>D7: 7.62x54mm UKR Stiletto<br/>D-Special (D-S): Undetermined, Emerging Threat"]];
	player createDiaryRecord ["Docs", ["System: HP WHITE 0500.2", "Independent testing standard of body armor that competes with NIJ 0101.06 / 0101.07 to some degree.<br/><br/>Level A: .38 Round Nose, 3 Shots<br/>Level B: 9x19mm FMJ, 3 Shots<br/>Level C: .44 Magnum FMJ, 3 Shots<br/>Level D: 7.62x51mm M80, 3 Shots<br/>Level E: .30-06 M2AP, 3 Shots"]];
	player createDiaryRecord ["Docs", ["System: UL 752", "Rating system for building reinforcement against ballistic threats.<br/><br/>L1: 9x19mm FMJ, 3 Shots<br/>L2: .357 Magnum JSP, 3 Shots<br/>Shotgun: 12-Gauge Slug, 3 Shots<br/>L3: .44 Magnum Semi-Wadcutter, 3 Shots<br/>L4: 30-06 Soft Point, 1 Shot<br/>L5: 7.62x51mm FMJ (M80), 1 Shot <br/>L6: 9x19mm FMJ, 5 Shots<br/>L7: 5.56x45mm FMJ, 5 Shots<br/>L8: 7.62x51mm M80, 5 Shots<br/>L9: 30-06 M2AP, 1 Shot<br/>L10: .50 BMG M2 Ball, 1 Shot"]];
	player createDiaryRecord ["Docs", ["Notes: STPs and Special Ratings", "The term STP or Special Threat Plate refers to a insert that is designed to tackle specific threats while also meeting certain challenges in the fields of weight and durability.<br/>In addition, there are also special designations that will give you further insight into an insert's ability.<br/>XSAPI Compliant: Indicates that an insert meets US Armed Forces requirements for the XSAPI program (7N37, 7N39, M993, M995)<br/>ICW: Indicates that an insert will only function In-Conjunction-With Level II or IIIA soft armor, as in a vest or a backer."]];
	player createDiaryRecord ["Docs", ["Notes: Uncommon Threat List", ".425 Express: Extremely uncommon .300 Winchester Magnum wildcat that pushes a muzzle energy of around 7,000 Joules firing a 400 grain bullet at 2,420 feet per second - MIL-VI or FBI-IV recommended for FMJ - MIL-VII recommended for AP<br/>.50 Beowulf: Slow commercialized daughter cartridge of 5.56x45mm NATO / .223 Remington. NIJ III with strong trauma protection recommended.<br/>.458 Whinchester Magnum: Slow old-school cartridge - only requires MIL-III and NIJ-III+ to stop, albeit with strong trauma considerations.<br/>1.6x41mm Flechette: AAI Corporation's star cartridge. Extremely difficult to stop - MIL-VII+ recommended.<br/>.50 GI: Necked-out .45 ACP - NIJ IIIA recommended but NIJ II will suffice<br/>7N47: Extremely obscure Russian 7.62x54R Tungsten SLAP ammunition. Probability of an encounter with this threat is extremely low - demands MIL-VI+<br/>.45 RAPTOR: 7.62x51mm Daughter Cartridge with impressive raw energy - MIL-V recommended due to concerns regarding trauma and BFD.<br/>9x90mm MEN: Mid-1990s prototype Anti-Materiel cartridge - virtually impossible to stop even with MIL-VIII*<br/>.600 OVERKILL: Heavyweight elephant rifle cartridge - MIL-VI recommended due to blunt trauma concerns."]];
	
};
